export const LOAD_PENDING = "LOAD_PENDING";
export const LOAD_RESOLVED = "LOAD_RESOLVED";
export const LOAD_ERROR = "LOAD_ERROR";

export const CREATE_PENDING = "CREATE_PENDING";
export const CREATE_RESOLVED = "CREATE_RESOLVED";
export const CREATE_ERROR = "CREATE_ERROR";

export const UPDATE_PENDING = "UPDATE_PENDING";
export const UPDATE_RESOLVED = "UPDATE_RESOLVED";
export const UPDATE_ERROR = "UPDATE_ERROR";

export const DELETE_PENDING = "DELETE_PENDING";
export const DELETE_RESOLVED = "DELETE_RESOLVED";
export const DELETE_ERROR = "DELETE_ERROR";

 export const DISPLAY_PERIOD_CHANGE = "DISPLAY_PERIOD_CHANGE";

export const SHIFT_SELECTED = "SHIFT_SELECTED";