export const LOAD_PENDING = "LOAD_PENDING";
export const LOAD_RESOLVED = "LOAD_RESOLVED";
export const LOAD_ERROR = "LOAD_ERROR";


export const LOAD_EVENTS_PENDING = "LOAD_EVENTS_PENDING";
export const LOAD_EVENTS_RESOLVED = "LOAD_EVENTS_RESOLVED";
export const CLEAR_EVENTS = "CLEAR_EVENTS";